{{- if .Values.externalSecrets.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.externalSecrets.clusterSecretStore.service }}
      region: {{ .Values.externalSecrets.clusterSecretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.clusterSecretStore.saName }}
            namespace: {{ .Values.externalSecrets.clusterSecretStore.saNamespace }}
{{- end }}
