apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations: { policies.kyverno.io/severity: high }
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: require-image-tag
    match: { any: [{ resources: { kinds: [Pod] } }] }
    exclude:
      any:
      - resources:
          namespaces: [kube-system, kyverno, monitoring, cert-manager, external-secrets, ingress-nginx, argocd]
    validate:
      message: "Image tag ':latest' or missing tag is not allowed. Pin a tag or digest."
      pattern:
        spec:
          containers:
          - image: "!*:latest"
  - name: require-image-tag-present
    match: { any: [{ resources: { kinds: [Pod] } }] }
    exclude:
      any:
      - resources:
          namespaces: [kube-system, kyverno, monitoring, cert-manager, external-secrets, ingress-nginx, argocd]
    validate:
      message: "An explicit image tag/digest is required."
      pattern:
        spec:
          containers:
          - image: "*:*"
