apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-requests-limits
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: validate-resources
    match: { any: [{ resources: { kinds: [Pod] } }] }
    exclude:
      any:
      - resources:
          namespaces: [kube-system, kyverno, monitoring, cert-manager, external-secrets, ingress-nginx, argocd]
    validate:
      message: "CPU/memory requests and limits are required on every container."
      pattern:
        spec:
          containers:
          - resources:
              requests: { memory: "?*", cpu: "?*" }
              limits: { memory: "?*", cpu: "?*" }
