apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Dev environment — team-dev may sync
  sourceRepos:
  - https://github.com/rksasi15/retail-platform-poc.git
  - https://kyverno.github.io/kyverno/
  - https://prometheus-community.github.io/helm-charts
  destinations:
  - server: https://kubernetes.default.svc
    namespace: argocd
  - server: https://kubernetes.default.svc
    namespace: retail-dev
  - server: https://kubernetes.default.svc
    namespace: monitoring
  - server: https://kubernetes.default.svc
    namespace: kube-system
  - server: https://kubernetes.default.svc
    namespace: kyverno
  clusterResourceWhitelist:
  - { group: "*", kind: "*" }
  namespaceResourceWhitelist:
  - { group: "*", kind: "*" }
