apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkout-dev
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: dev
  source:
    repoURL: "https://github.com/rksasi15/retail-platform-poc.git"
    targetRevision: main
    path: apps/retail-service
    helm:
      valueFiles: [values-checkout-dev.yaml]
  destination: { server: https://kubernetes.default.svc, namespace: retail-dev }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
    retry: { limit: 3, backoff: { duration: 10s, factor: 2, maxDuration: 2m } }
